### ISSUE TITLE
Skipping port option crashes app

### ISSUE THREAD

**Issue by vorg** [szymonkaliski/sketchbook-cli#1]
Works `sketchbook-cli . --port 3099`

Crash `sketchbook-cli .`

```bash
TypeError: (options.port || []).reduce is not a function
    at getPort (/usr/local/lib/node_modules/sketchbook-cli/node_modules/get-port/index.js:23:30)
    at module.exports.options (/usr/local/lib/node_modules/sketchbook-cli/node_modules/get-port/index.js:32:2)
    at Object.<anonymous> (/usr/local/lib/node_modules/sketchbook-cli/index.js:272:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
```

**Comment by szymonkaliski** [comment]
Thanks, fixed with https://github.com/szymonkaliski/sketchbook-cli/commit/90d7f82983b2743b9081ee193ca7e8c3359b68e1, npm version `1.4.2`
